title: "The Cyber Project"
author: "I.H"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "HOME.md", title: "Home", url: "/"}
  - {file: "PROJECTS.md", title: "Projects", url: "/projects/"}
  - {file: "posts.html", title: "Posts", url: "/posts/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:thecyberproject.sandstorm424@aleeas.com"}
  - {title: Github, icon: github, url: "https://github.com/IlmHe"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/ilmar/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-gist

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://thecyberproject.fi" # the base hostname & protocol for your site
